DROP DATABASE IF EXISTS proyecto;
CREATE DATABASE proyecto;
USE proyecto;

CREATE TABLE alumno(
    id SMALLINT(5) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(15) NOT NULL UNIQUE,
    password VARCHAR(14) NOT NULL,
    nombre VARCHAR(50),
    email VARCHAR(100) NOT NULL UNIQUE,
    fecha DATE  
)ENGINE=InnoDB;

CREATE TABLE categoria(
    id SMALLINT(5) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE examen(
    id SMALLINT(5) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(50) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE al_ca_ex(
    id_exa SMALLINT(5) UNSIGNED,
    id_cat SMALLINT(5) UNSIGNED,
    id_alu SMALLINT(5) UNSIGNED,
    CONSTRAINT PK_ALCAEX PRIMARY KEY (id_exa),
    CONSTRAINT FK_ALCAEX_IDEXA FOREIGN KEY (id_exa) REFERENCES examen(id),
    CONSTRAINT FK_ALCAEX_IDCAT FOREIGN KEY (id_cat) REFERENCES categoria(id),
    CONSTRAINT FK_ALCAEX_IDAL FOREIGN KEY (id_alu) REFERENCES alumno(id)
)ENGINE=InnoDB;


CREATE TABLE pregunta(
    id SMALLINT(5) UNSIGNED AUTO_INCREMENT,
    id_exa SMALLINT(5) UNSIGNED,
    tipo SET('N','R') NOT NULL,
    respuesta TINYTEXT NOT NULL,
    cuestion TINYTEXT NOT NULL,
    CONSTRAINT PK_PRE PRIMARY KEY (id,id_exa),
    CONSTRAINT FK_PRE_EXA FOREIGN KEY (id_exa) REFERENCES examen(id) ON DELETE CASCADE
)ENGINE=InnoDB;
